user:
  authentication:
    secretKey: fc1fa54106ef406a49b528e12caf62f49fee9cef9b082e1022a10027fd8c35fd

spring:
  application:
    name: backend

  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backenddb

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
